# Config for CaptureMob
# Flag mobs as catchable.

tntSnowball:
    enabled: false
    range: 3
mobCatch:
    enabled: true
    cost: 371
    chance: 50
    mobs:
        Creeper: true
        Skeleton: true
        Spider: true
        Zombie: true
        Slime: true
        Ghast: true
        PigZombie: true
        Enderman: true
        CaveSpider: true
        Silverfish: true
        Blaze: true
        LavaSlime: true
        Pig: true
        Sheep: true
        Cow: true
        Chicken: true
        Squid: true
        Wolf: true
        MushroomCow: true
        SnowMan: false
        Ozelot: true
        VillagerGolem: false
        Villager: true
displayTable:
    enabled: true
    tableblocks:
    - 20
    - 35
    - 41
    - 42
    - 44
    - 57
    - 98