# Config for CaptureMob
# Flag mobs as catchable.

tntSnowball:
    enabled: true
    range: 3
mobCatch:
    enabled: true
    cost: 371
    mobs:
        Creeper: true
        Skeleton: true
        Spider: false
        Zombie: true
        Slime: true
        Ghast: true
        PigZombie: true
        Enderman: true
        CaveSpider: false
        Silverfish: true
        Blaze: true
        LavaSlime: true
        Pig: true
        Sheep: true
        Cow: true
        Chicken: true
        Squid: true
        Wolf: true
        MushroomCow: false
        SnowMan: false
        Ozelot: true
        VillagerGolem: false
        Villager: false
displayTable:
    enabled: true
    tableblocks:
    - 1
    - 35
    - 41
    - 42
    - 44
    - 57
    - 89
    - 98
    - 123
    - 124