# Config for CaptureMob
# Flag mobs as catchable.

tntSnowball:
    enabled: false
    range: 3
mobCatch:
    enabled: true
    cost: 371
    chance: 50
    mobs:
        Creeper: false
        Skeleton: false
        Spider: false
        Zombie: false
        Slime: false
        Ghast: false
        PigZombie: false
        Enderman: false
        CaveSpider: false
        Silverfish: false
        Blaze: false
        LavaSlime: false
        Pig: true
        Sheep: true
        Cow: true
        Chicken: true
        Squid: true
        Wolf: true
        MushroomCow: false
        SnowMan: false
        Ozelot: true
        VillagerGolem: false
        Villager: false
displayTable:
    enabled: true
    tableblocks:
    - 35
    - 44
    - 98