name: Brabotools
main: com.leovanhaaren.brabotools.Brabotools
version: 0.5
author: Leo
description: Plugin for catching mobs with eggs.
commands:
    displaytables:
        description: Command for reloading all Display Tables!
        usage: /<command> [reload]